package net.eltown.servercore.components.roleplay;

public enum RoleplayID {

    SHOP_MINER,
    SHOP_NETHER,
    SHOP_EXPLORER,
    SHOP_LUMBERJACK,
    SHOP_MONSTERHUNTER,
    SHOP_BLACKSMITH,
    SHOP_FISHERMAN,

    JOB_BANKER,
    JOB_CRYPTO,
    JOB_COOK,
    JOB_FARMER,
    JOB_TAILOR,

    TOWNHALL_RECEPTION,
    TOWNHALL_TAXES,
    TOWNHALL_BUILDING,
    TOWNHALL_COURT,
    TOWNHALL_ARCHIVE,
    TOWNHALL_ADVICE_BUREAU_1,
    TOWNHALL_ADVICE_BUREAU_2,
    TOWNHALL_ADVICE_BUREAU_3,

    FEATURE_LOLA,
    FEATURE_JOHN,
    FEATURE_AINARA,
    FEATURE_MIKE,
    FEATURE_BRIAN,
    FEATURE_ROB,
    FEATURE_ANNA,
    FEATURE_CARLA,

    UTIL_ATM

    ;

}
