package net.eltown.servercore.components.roleplay;

public enum RoleplayID {

    SHOP_MINER,
    SHOP_NETHER,
    SHOP_EXPLORER,
    SHOP_LUMBERJACK,
    SHOP_MONSTERUNTER,
    SHOP_BLACKSMITH,

    BANKER,
    CRYPTO,
    COOK,
    FARMER,

    TOWNHALL_RECEPTION,
    TOWNHALL_TAXES,
    TOWNHALL_BUILDING,
    TOWNHALL_COURT,
    TOWNHALL_ARCHIVE,

    FEATURE_LOLA,
    FEATURE_JOHN,
    FEATURE_AINARA,
    FEATURE_MIKE,
    FEATURE_BRIAN,
    FEATURE_ROB,
    FEATURE_ANNA,
    FEATURE_CARLA,

    ;

}
